### Project specific config ###
language: r
cache: packages

install:
  - Rscript -e 'install.packages("lintr")'

matrix:
  include:
    - os: linux
      r: release
      env: ATOM_CHANNEL=stable

    - os: linux
      r: release
      env: ATOM_CHANNEL=beta

env:
  global:
    LINTR_COMMENT_BOT=false

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^greenkeeper/.*$/

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
